let year = document.querySelector('.year')
let month = document.querySelector('.month')
let day = document.querySelector('.dia')
let tipo = document.querySelector('.tipo')
let desc = document.querySelector('.desc')
let btnSave = document.querySelector('.btn')
let cont = document.querySelector('.cont')